# Parameters for the audio pre-processing pipeline
[audio_processing]
lowpass_cutoff_hz = 5500
compressor_threshold_db = -12.0
compressor_ratio = 2.5
sample_rate = 44100             # Standard CD quality sample rate

# Parameters defining the physical geometry of the groove
[groove_geometry]
groove_pitch_mm = 0.158    # Standard for microgroove records
groove_top_width_mm = 0.06
groove_depth_mm = 0.025
amplitude_scale = 1.0      # Scales the audio modulation depth

# Physical dimensions of the final record (7-inch single)
[record_dimensions]
record_diameter_mm = 177.8
center_hole_diameter_mm = 7.24
record_thickness_mm = 1.5
lead_in_groove_mm = 5.0        # Blank space from edge to start of audio

# Assumed parameters of the target 3D printer for reference
[printer_profile]
name = "Default High-Resolution Resin Printer"
layer_height_mm = 0.025
